name: Testing

on:
    pull_request:
        types: [closed]
        branches: [main]

env:
  workspaceId: "364397913113100291"
  memberId: "364404407103651845"
  channelId: "364397913113165830"
  trickleId: "578759146069819400"

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            # Pull Code
            - name: Pull repo
              uses: actions/checkout@v2

            # Save lambda invoke result
            - name: Check pull_request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.sender.login }}
                echo ${{ github.event.pull_request.commits_url }}
                echo ${{ github.event.pull_request.head.ref }} --> ${{ github.event.pull_request.base.ref }}
                echo "${{ github.event.pull_request.body }}" > prbody.txt
            
            # Generate trickle blocks
            - name: Generate trickle blocks
              id: getBlockData
              run: |
                content=`python3 generate_pr_tmpt.py -t "${{ github.event.pull_request.title }}" -b prbody.txt`
                echo "::set-output name=blockDataJson::$content"

            # Send trickle
            - name: Send trickle
              uses: visionwx/trickle-sender@v1.0.4
              with:
                trickleToken: ${{ secrets.trickleToken }}
                workspaceId: ${{ env.workspaceId }}
                memberId: ${{ env.memberId }}
                channelId: ${{ env.channelId }}
                blockType: trickle
                blockData: '${{ steps.getBlockData.outputs.blockDataJson }}'