name: Testing

on:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            # Pull Code
            - name: Pull repo
              uses: actions/checkout@v2

            # Save lambda invoke result
            - name: Check pull_request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.pull_request.body }}
                echo ${{ github.event.sender.login }}