name: Testing

on:
    pull_request:
        types: [closed]
        branches: [main]

# env:
#   workspaceId: "364397913113100291"
#   memberId: "409788576109166597"
#   channelId: "364397913113165830"
#   trickleId: "590432394733944840"

    # TRICKLE_WORKSPACE_ID: "30788161542029315"
    # TRICKLE_MEMBER_ID: "422649524830339077"
    # TRICKLE_CHANNEL_ID: "264823540841447430"
    # TRICKLE_ID: "590908299793137672"

env:
  TRICKLE_WORKSPACE_ID: ${{ secrets.TRICKLE_WORKSPACE_ID }}
  TRICKLE_MEMBER_ID: ${{ secrets.TRICKLE_MEMBER_ID }}
  TRICKLE_CHANNEL_ID: ${{ secrets.TRICKLE_CHANNEL_ID }}
  DEV_TRICKLE_ID: ${{ secrets.DEV_TRICKLE_ID }}

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            # Pull Code
            - name: Pull repo
              uses: actions/checkout@v2

            # Save lambda invoke result
            - name: Check pull_request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.sender.login }}
                echo ${{ github.event.user.login }}
                echo ${{ github.event.pull_request.commits_url }}
                echo ${{ github.event.pull_request.head.ref }} --> ${{ github.event.pull_request.base.ref }}
                echo "${{ github.event.pull_request.body }}" > prbody.txt
            
            # Generate trickle blocks
            # - name: Generate trickle blocks
            #   id: getBlockData
            #   run: |
            #     content=`python3 generate_pr_tmpt.py -t "${{ github.event.pull_request.title }}" -b prbody.txt`
            #     echo "::set-output name=blockDataJson::$content"

            # Send trickle
            - name: Send trickle comment
              uses: visionwx/trickle-sender@v1.0.4
              with:
                trickleToken: ${{ secrets.trickleToken }}
                workspaceId: ${{ env.TRICKLE_WORKSPACE_ID }}
                memberId: ${{ env.TRICKLE_MEMBER_ID }}
                channelId: ${{ env.TRICKLE_CHANNEL_ID }}
                trickleId: ${{ env.DEV_TRICKLE_ID }}
                blockType: comment
                blockData: '[{"type":"text","value":"--> Hello all, DEV Env Updated, from ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}, trigger by ${{ github.event.sender.login }}"}]'
