name: Testing

on:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            # Pull Code
            - name: Pull repo
              uses: actions/checkout@v2

            # Save lambda invoke result
            - name: Check pull_request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.sender.login }}
                echo ${{ github.event.pull_request.commits_url }}
                echo ${{ github.event.pull_request.head.ref }} --> ${{ github.event.pull_request.base.ref }}
                echo "${{ github.event.pull_request.body }}" > pr_body.txt
                cat pr_body.txt