name: Testing AWS

on:
    workflow_dispatch:

env:
    AWS_S3_KEY_ID: ${{ secrets.AWS_S3_KEY_ID }}
    AWS_S3_KEY_SECRET: ${{ secrets.AWS_S3_KEY_SECRET }}
    AWS_S3_BUCKET_NAME: boom2-resource
    AWS_S3_COMPONENT_BUCKET_NAME: trickle-component
    AWS_S3_REGION: us-east-1
    AWS_CLOUD_FRONT_DISTRIBUTION_ID: E28OIAI99C3YGA
    AWS_DEPLOY_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
    AWS_DEPLOY_SECRET: ${{ secrets.AWS_DEPLOY_SECRET }}
    AWS_LAMBDA_FUNCTION_NAME: trickle_ssr_dev
    ECR_REGISTRY: 257417524232.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_NAME: trickle-ssr
    AWS_DEFAULT_REGION: us-east-1
    AWS_LAMBDA_EDGE_FUNCTION_NAME: trickle_edge_dev
    AWS_S3_LAMBDA_PACKAGE_BUCKET_NAME: lambda-package-20220712
    workspaceId: "364397913113100291"
    memberId: "364404407103651845"
    channelId: "364397913113165830"
    trickleId: "578759146069819400"

jobs:
    test_invoke_lambda:
        name: test_invoke_lambda
        runs-on: ubuntu-latest
        steps:
            # Pull Code
            - name: Pull repo
              uses: actions/checkout@v2

            # Configure AWS S3
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ env.AWS_DEPLOY_KEY }}
                  aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET }}
                  aws-region: ${{ env.AWS_S3_REGION }}
            
            # Get last day
            - name: Get last day
              id: get-date
              run: |
                date -d "1 day ago" +"%Y-%m-%d"

            # Send Query Request
            - name: Send query reuqest
              id: query
              run: |
                ldate=`date -d "1 day ago" +"%Y-%m-%d"`
                cdate=`date +"%Y-%m-%d"`
                aws logs start-query \
                  --log-group-name API_GW_LIVE_V1 \
                  --start-time `date -d "$ldate 00:00:00" +%s` \
                  --end-time `date -d "$cdate 00:00:00" +%s` \
                  --query-string 'fields @timestamp, @message | stats count() by bin(15m)' > query_request.json
                content=`cat query_request.json`
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=queryResult::$content"

            # sleep 10s
            - name: Sleep for 10s
              uses: juliangruber/sleep-action@v1
              with:
                time: 10s

            # Get Query Result
            - name: Get query result
              run: |
                ldate=`date -d "1 day ago" +"%Y-%m-%d"`
                echo "${{fromJson(steps.query.outputs.queryResult).queryId}}"
                aws logs get-query-results --query-id ${{fromJson(steps.query.outputs.queryResult).queryId}} > query_result.json
                mv query_result.json rps_result.json
                python3 parse_rps_result.py
                mkdir -p out/$ldate
                cp rps.html out/$ldate
                cp rps.html.json out/$ldate
            
            # Upload report
            - name: Upload report
              id: upload
              run: |
                ldate=`date -d "1 day ago" +"%Y-%m-%d"`
                aws s3 sync out/$ldate s3://${{ env.AWS_S3_BUCKET_NAME }}/miniapps/$ldate
                reportUrl=https://devres.trickle.so/miniapps/$ldate/rps.html
                echo "::set-output name=reportUrl::$reportUrl"

            # Send trickle
            - name: Send trickle
              uses: visionwx/trickle-sender@v1.0.4
              with:
                trickleToken: ${{ secrets.trickleToken }}
                workspaceId: "364397913113100291"
                memberId: "409788576109166597"
                channelId: "364397913113165830"
                blockType: trickle
                blockData: '[{"type":"embed","value":"${{ steps.upload.outputs.reportUrl }}"}]'